require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PhasesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Phase. As you add validations to Phase, be sure to
  # adjust the attributes here as well.
   let(:valid_attributes) {{
    :start_date_phase => "21/02/2014",
    :end_date_phase => "23/05/2014" , :created_at => "09/10/2014",
    :updated_at => "10/07/20140"
  }}
  

  let(:invalid_attributes) {{
    :start_date_phase => "13/02/2014",
    :end_date_phase => "12/02/2014" , :created_at => "12/10/2014",
    :updated_at => "10/11/2014"
 }}

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PhasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all phases as @phases" do
      phase = Phase.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:phases)).to eq([phase])
    end
  end

  describe "GET show" do
    it "assigns the requested phase as @phase" do
      phase = Phase.create! valid_attributes
      get :show, {:id => phase.to_param}, valid_session
      expect(assigns(:phase)).to eq(phase)
    end
  end

  describe "GET new" do
    it "assigns a new phase as @phase" do
      get :new, {}, valid_session
      expect(assigns(:phase)).to be_a_new(Phase)
    end
  end

  describe "GET edit" do
    it "assigns the requested phase as @phase" do
      phase = Phase.create! valid_attributes
      get :edit, {:id => phase.to_param}, valid_session
      expect(assigns(:phase)).to eq(phase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Phase" do
        expect {
          post :create, {:phase => valid_attributes}, valid_session
        }.to change(Phase, :count).by(1)
      end

      it "assigns a newly created phase as @phase" do
        post :create, {:phase => valid_attributes}, valid_session
        expect(assigns(:phase)).to be_a(Phase)
        expect(assigns(:phase)).to be_persisted
      end

      it "redirects to the created phase" do
        post :create, {:phase => valid_attributes}, valid_session
        expect(response).to redirect_to(Phase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phase as @phase" do
        post :create, {:phase => invalid_attributes}, valid_session
        expect(assigns(:phase)).to be_a_new(Phase)
      end

      it "re-renders the 'new' template" do
        post :create, {:phase => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
    let(:valid_attributes) {{
    :start_date_phase => "21/02/2014",
    :end_date_phase => "23/05/2014" , :created_at => "09/10/2014",
    :updated_at => "10/07/20140"}
        
    }

      it "updates the requested phase" do
        phase = Phase.create! valid_attributes
        put :update, {:id => phase.to_param, :phase => valid_attributes}, valid_session
        phase.reload
        
      end

      it "assigns the requested phase as @phase" do
        phase = Phase.create! valid_attributes
        put :update, {:id => phase.to_param, :phase => valid_attributes}, valid_session
        expect(assigns(:phase)).to eq(phase)
      end

      it "redirects to the phase" do
        phase = Phase.create! valid_attributes
        put :update, {:id => phase.to_param, :phase => valid_attributes}, valid_session
        expect(response).to redirect_to(phase)
      end
    end

    describe "with invalid params" do
      it "assigns the phase as @phase" do
        phase = Phase.create! valid_attributes
        put :update, {:id => phase.to_param, :phase => invalid_attributes}, valid_session
        expect(assigns(:phase)).to eq(phase)
      end

      it "re-renders the 'edit' template" do
        phase = Phase.create! valid_attributes
        put :update, {:id => phase.to_param, :phase => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phase" do
      phase = Phase.create! valid_attributes
      expect {
        delete :destroy, {:id => phase.to_param}, valid_session
      }.to change(Phase, :count).by(-1)
    end

    it "redirects to the phases list" do
      phase = Phase.create! valid_attributes
      delete :destroy, {:id => phase.to_param}, valid_session
      expect(response).to redirect_to(phases_url)
    end
  end

end
